module.exports = {
    auth: require("./auth/auth"),
    accessTokenRequest: require('./auth/accessTokenRequest'),
    refreshTokenRequest: require('./auth/refreshTokenRequest'),
    signup: require("./user/signup"),
    login: require("./user/login"),
    logout: require("./user/logout"),
    search: require("./search/search"),
    // email: require("./notification/email"),
    mainpage: require("./mainpage/mainpage"),
    userinfo: require("./mypage/userinfo"),
    editUserinfo: require("./mypage/editUserInfo"),
    withdrawal: require("./mypage/withdrawal"),
    setLocations: require("./locations/setLocations"),
    unsetLocations: require("./locations/unsetLocations"),
    userLocations: require("./locations/userLocations"),
  };